<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="https://github.com/htapia/TallerPythonIntroCienciaDatos/blob/master/notebooks/figures/header_small.png?raw=1">

*Esta libreta contiene material del Taller de Python que se lleva a cabo como parte del 
evento [Data Challenge Industrial 4.0](www.lania.mx/dci). El contenido ha sido adaptado 
por HTM y GED a partir del libro [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) 
de Jake VanderPlas y se mantiene la licencia sobre el texto, 
[CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode), 
y sobre el codigo [MIT license](https://opensource.org/licenses/MIT).*

<!--NAVIGATION-->
< [Tipos de Datos en Python](01.01-Understanding-Data-Types.ipynb) | [Contenido](Index.ipynb) | [Cálculos con Arrays 1. Ufuncs](01.03-Computation-on-arrays-ufuncs.ipynb) >

<a href="https://colab.research.google.com/github/htapia/TallerPythonIntroCienciaDatos/blob/master/notebooks/01.02-The-Basics-Of-NumPy-Arrays.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>


# Basicos de NumPy: arreglos

Categorias de manipulaciones básicas de arreglos:

- *Atributos de arrays*
- *Indexado de arrays*
- *Rebanadas de arrays*
- *Reformado de arrays*
- *Union y separación de arrays*

## Atributos de Arrays

In [0]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [0]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [0]:
print("dtype:", x3.dtype)

dtype: int64


In [0]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


## Indexado de Arrays : Acceso a elementos individuales

In [0]:
x1

array([5, 0, 3, 3, 7, 9])

In [0]:
x1[0]

5

In [0]:
x1[4]

7

In [0]:
x1[-1]

9

In [0]:
x1[-2]

7

In [0]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [0]:
x2[0, 0]

3

In [0]:
x2[2, 0]

1

In [0]:
x2[2, -1]

7

In [0]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [0]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## Rebanadas de Arrays: Accesa a partes (subarrays)

``` python
x[start:stop:step]
```


### Uni-dimensionales

In [0]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [0]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [0]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [0]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [0]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [0]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [0]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### Multi-dimensionales


In [0]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [0]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [0]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [0]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accesando renglones y columnas del array

In [0]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [0]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In [0]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


### Subarrays son vistas y no copias

- Es importante, y práctico, entender que las rebanadas de arrays son *vistas* del trozo y no *copias* del subarray

In [0]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


extraer un subarray de $2 \times 2$ de éste:

In [0]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Ahora si modificamos este subarray, el array original también cambia! Miren:

In [0]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [0]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


- Este comportamiento es de utilidad pues se pueden acceder y procesar partes de los arrays sin tener que hacer copias de ellos

### Creando copias de arrays

- En ocasiones será práctico crear copias explícitas de los datos
- Esto se hace con el método ``copy()``:

In [0]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


Si ahora modificamos este subarray, el original no cambia:

In [0]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [0]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reformado (reshaping) de Arrays

- Podemos cambiar la forma (reformar) de un array usando el método ``reshape``
Por ejemplo, si queremos los número del 1 al 9 en un array de $3 \times 3$, podemos hacer lo siguiente:

In [0]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [0]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [0]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [0]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

##  Concatenación y Separación de Arrays

- Es posible  combinar multiples arrays en uno
- Es posible separar un array a multiples arrays

### Concatenación de arrays

Concatenacion, o unión de dos arrays en NumPy, se puede hacer con ``np.concatenate``, ``np.vstack``, y ``np.hstack``.
``np.concatenate`` toma una tupla o lista de arrays como primer argumento:

In [0]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [0]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [0]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [0]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [0]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [0]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [0]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Separación de arrays

El opuesto a la concatenación es la sepación, implementada en las funciones ``np.split``, ``np.hsplit``, y ``np.vsplit``.  Para cada una de éstas podemos pasar una lista de índices en donde se quiere hacer la separación:

In [0]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


*N* puntos-de-separación, crean *N + 1* subarrays.

In [0]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [0]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


<!--NAVIGATION-->
< [Tipos de Datos en Python](01.01-Understanding-Data-Types.ipynb) | [Contenido](Index.ipynb) | [Cálculos con Arrays 1. Ufuncs](01.03-Computation-on-arrays-ufuncs.ipynb) >

<a href="https://colab.research.google.com/github/htapia/TallerPythonIntroCienciaDatos/blob/master/notebooks/01.02-The-Basics-Of-NumPy-Arrays.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>
